[tool.poetry]
name = "tins_test_data"
version = "0.1.0"
description = ""
authors = ["heitor <hfcredidio@gmail.com>"]

[tool.poetry.dependencies]
python = "^2.7"
scipy = "^1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
